name: 📊 WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
